[tool.black]
line-length = 100
target-version = ['py37']
exclude = '''(
    \(
        dist
        | docs
        | \.tox
        | \.hg
        | \.mypy_cache
        | \.pytest_cache
        | __pycache__
        | logilab_common.egg-info
    \)
)'''
